---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: ci-cd
spec:
  encryptedData:
    password: AgCV+aS0jLi6xBmClu1qumuME4hn0nxEmZ3BCvXsp9TH9xYK1j/tsyYR8NaGwCBiaG/CHrsP5wDCxrqdfDmHoOpu1mtcPhAPEfoLDsaqvH971io7MHzLf8FJfUzKWk+OKj0zjmpehSzswcZ2TmadLvGbCPbfP/Jg+YVqESQybV0icaslcmh0HrqDNkHUrSAKCWQRbwLJt2GAURV6X2ucYKEQhDjtykZWtAvUaAr/lLCX/BrRQUG86C34L8F4G7LS8x9BJyEwiQYCbt+1SHx5j5tJIYR3WwZZweFsxPRcAoFYay7AngM8ALSD0Slyb7NDzd/g78e/LeQYbyVUGZ7cnmxjJ6OzcdA1KJQEud6R1ttbNTXxi5QaNt/B4uLlEQzo2A8Deldcty7arRH9yDEQLVbJP5QZTc2/q/hVsIWBaFb21Nhv4ep085J25VWRprq/nVQ0b+YN8lGQV9qFX9IHvBmVzpfyvVOAaQ4QIfIyLW9gxJW0gp5fZEVpvtKXEhRk3QAQIDkIDOuQRFxcZfIvYGwMKfXBsBDi6UzW9n+GVCORu/SR8+9Ah27/zvBzMfH72TeEPW4GtwoDBnAjAsezGWLg6ouTdH9p8BGvjC0DYDzsGahpw5CZ/mVxyUoCOpDEFhKbQomJpT+VOjxucJ5jkHeXr450oeqQk4v2FrDytDEIrlMi5qRpQLZUASW5zOR9Nd7wmvKRA8n2IcXFbRolQA==
  template:
    metadata:
      name: demo-secret
      namespace: ci-cd
